import Container from "@/components/container";
import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";

const ptSans = PT_Sans({
  style: ["normal"],
  weight: "400",
  subsets: ["cyrillic-ext"],
});

export const metadata: Metadata = {
  title: "Girish Chaudhari",
  description: "Generated by Girish Chaudhari",
  authors: [{ name: "Girish Chaudhari", url: new URL("https://gdev.net") }],
  applicationName: "gdev.net",
  creator: "Girish Chaudhari",
  icons: [
    {
      rel: "icon",
      url: "/avatar.png",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <main
            id="skip"
            className="flex flex-col justify-center px-8 bg-gray-50 dark:bg-gray-900"
          >
            <Header />
            <Container>{children}</Container>
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
